admintool/urls.py
from django.conf.urls import patterns, include, url
from admintool import views

urlpatterns = patterns('admintool.views',
    url(r'^$', views.index, name='index'),
    url(r'^add/$',views.add_expense, name = 'add_expense'),
    url(r'^save/$', views.save_expense, name = 'save_expense'),
    url(r'^delete/$', views.delete_expense, name = 'delete_expense'),
    url(r'^update/$', views.update_expense, name = 'update_expense'),
    url(r'^upload/$', views.upload_target, name = 'upload_expense_csv'),
)

track_expenses/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'track_expenses.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^expenses/', include('admintool.urls')),
    url(r'^api/v1/', include('admintool.json_urls')),
#    url(r'^upload_target/$', 'admintool.views.upload_target'),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
    url(r'^$', TemplateView.as_view(template_name='homepage.html'), name="home"),
)

admintool/models.py
from django.db import models
# Create your models here.
from django.contrib.auth.models import User

class ExpenseCategory( models.Model):
    category_name = models.CharField(max_length=25) 
    category_desc = models.CharField(max_length=50)

    def __unicode__(self):
        return u'%s %s ' % ( self.category_name, self.category_desc )
    
class ExpenseType( models.Model):
    type_name = models.CharField(max_length=25)
    type_desc = models.CharField(max_length=50)

    def __unicode__(self):
        return u'%s %s' % ( self.type_name, self.type_desc )

class VendorType( models.Model):
    vendor_name = models.CharField(max_length=25)
    vendor_desc = models.CharField(max_length=50)

    def __unicode__(self):
        return u'%s %s' % ( self.vendor_name,  self.vendor_desc )

class Expense(models.Model):
    #created_on : This is the default system date indicating when the expense was loaded into the system.

    #expense_date: This is the date when the actual  expense was incurred. This
    # date will  be of importance since all  queries will be based out of this
    # date

    expenseCategory = models.ForeignKey( ExpenseCategory)
    expenseType = models.ForeignKey ( ExpenseType )
    vendorType = models.ForeignKey ( VendorType)
    expense_date = models.DateField()
    amount_spent = models.DecimalField(max_digits=10, decimal_places=2)
    comments = models.CharField(max_length=100)
    created_by = models.ForeignKey (User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "Expense " + str(self.expense_date)+ " Amount = " + str(self.amount_spent)

class ExpenseTarget(models.Model):
    plan_type = models.CharField(max_length=25)
    expenseCategory = models.ForeignKey( ExpenseCategory )
    yr_m = models.CharField( max_length=10 )
    amount = models.DecimalField( max_digits=10, decimal_places=2 )
#    user=models.CharField( max_length=25) 
    user = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
  
    def __unicode__(self):
        return "Expense Target " +  plan_type +  " Year month " + yr_m +  " Amount = " + str(self.amount)  

admintool/forms.py
from django import forms
from admintool.models import ExpenseCategory, ExpenseType, VendorType, Expense

def clean_amount_spent(self):
    print "Into clean_amount_spent" 
    amount_spent = self.cleaned_data['amount_spent']
    if amount_spent <= 0:
        raise forms.ValidationError("Amount Spent must be greater than zero:" )
    return amount_spent 

def clean_expense_date(self):
    print "Into clean_expense_date" 
    expense_date = self.cleaned_date['expense_date']
    if expense_date is None:
        raise forms.ValidationError("Expense Date cannot be blank:")
    return expense_date	

class ExpenseForm(forms.Form):
    expenseCategory = forms.ModelChoiceField(label="Expense Category", queryset=ExpenseCategory.objects.all() , required=False, empty_label=None )
    expenseType =  forms.ModelChoiceField(label="Expense Type", queryset=ExpenseType.objects.all(), required=False, empty_label=None ) 
    vendorType =   forms.ModelChoiceField(label= "Vendor Type" , queryset=VendorType.objects.all(), required=False,  empty_label=None ) 
    expense_date = forms.DateField(label = "Expense Date",  required=False )
    amount_spent  = forms.DecimalField(label="Amount Spent" , required=False)
    comments =  forms.CharField(label="Comments" , required=False, widget=forms.Textarea)

    class Meta:
        model=Expense
        fields = ('expenseCategory', 'expenseType', 'vendorType', 'expense_date', 'amount_spent' ,  'comments' )

admintool/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext
from django.template import Context,loader
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseNotFound,HttpResponseRedirect
from django.core.urlresolvers import reverse
import datetime 
import csv
from admintool.forms import ExpenseForm
import logging 
from admintool.forms import ExpenseForm
from admintool.models import ExpenseCategory, ExpenseType, VendorType, Expense, ExpenseTarget
from admintool.serializers import ExpenseCategorySerializer
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


from django.contrib.auth.models import User


logger=logging.getLogger(__name__)

# Returns all expenses ordered by updated on
@login_required(login_url='/login')
def index(request):
    all_expenses = Expense.objects.filter(created_by=request.user).order_by('updated_on')
    expenseCategory = ExpenseCategory.objects.all()
    expenseType = ExpenseType.objects.all()
    vendorType = VendorType.objects.all()
 
    #t = loader.get_template('admintool/index.html')
    #c = Context({'all_expenses':all_expenses,'expenseCategory':expenseCategory, 'expenseType':expenseType,'vendorType':vendorType })
    #return HttpResponse(t.render(c))
    
    return render(request, 'admintool/index.html', {'all_expenses':all_expenses,'expenseCategory':expenseCategory, 'expenseType':expenseType,'vendorType':vendorType })
    
# I  have written the two methods below to test the logging from the Django Shell. We can remove these after we have a grip on the logging framework.
def test_logging():
    print("name is : " + __name__)
    logger.debug("Test Logging, This is a debug message:" ) 

def test_logging_v1():
    logger.info( "Test Logging This is a info message:" ) 

@login_required(login_url='/login')
def add_expense(request):
    logger.info("Into add_expense():" )
    errors =[]
    context = RequestContext(request)
 
    if request.method == "GET":
        form = ExpenseForm(request.GET)

        if form.is_valid():
            #return render( request,  'admintool/add_expense.html' ,{'form':form, 'all_expenses':all_expenses, 'expenseCategory':expenseCategory, 'expenseType':expenseType, 'vendorType':vendorType} )             
            return render( request,  'admintool/add_expense.html' ,{'form':form,} )  
        else:
            print form.errors
    else:
        form1=ExpenseForm()

    return render(request, 'admintool/add_expense.html' , {'errors':errors} )

@login_required(login_url='/login')

def save_expense(request):
    logger.info("Into save_expense:" ) 
    errors=[]
    if request.method == "POST":
        form=ExpenseForm(request.POST)
    else:
        form = ExpenseForm()
        return render (request, 'admintool/add_expense.html', {'form':form})
   
    expenseCategory = request.POST["expenseCategory"]
    expenseType = request.POST["expenseType"]
    vendorType = request.POST["vendorType"]
    expense_date = request.POST["expense_date"]
    amount_spent = request.POST["amount_spent"] 
    comments = request.POST["comments"]
    
    if len(expense_date) == 0  and len(amount_spent) == 0:
        messages.error(request, "Expense Date is a required field:" )
        messages.error(request, "Amount Spent is a required field:" )
        return render(request, 'admintool/add_expense.html', {'form':form}) 
    if len(expense_date) == 0:
        print "Into  expense_date is  None" 
        messages.error(request, "Expense Date is a required field:") 
        return render( request, 'admintool/add_expense.html', {'form':form})
    if len(amount_spent) == 0:  
        messages.error(request, "Amount Spent is a required field:" )
        return render( request, 'admintool/add_expense.html', {'form':form})
    if float(amount_spent) <=  0:
        messages.error(request, "Amount spent must be greater than zero") 
        return render( request, 'admintool/add_expense.html', {'form':form})

    datetime.datetime.strptime(expense_date,'%b %d, %Y')
    ec=Expense(expenseCategory = ExpenseCategory(expenseCategory),
               expenseType = ExpenseType(expenseType) ,
               vendorType = VendorType( vendorType),
               expense_date =  datetime.datetime.strptime(expense_date,'%b %d, %Y') ,
               amount_spent = amount_spent , 
               comments = comments ,
               created_by = request.user)
    ec.save()
    messages.success( request, "The Expense was saved successfully." )
    return redirect('/expenses')

@login_required(login_url='/login')
@csrf_exempt
def update_expense(request):
  
    print "In Update"
    logger.info("Into update_expense() :" ) 
    id = request.POST["id"]
    expenseCategory = request.POST["expenseCategory"]
    expenseType = request.POST["expenseType"]
    vendorType = request.POST["vendorType"]
    expense_date = request.POST["expense_date"]
    amount_spent = request.POST["amount_spent"] 
    #comments = request.POST["comments"]
    try:
        exp = Expense.objects.get(pk=id)
    except ObjectDoesNotExist:
        return HttpResponse("Error, Could not find record for id : " + id   ) 
    
    if len(expense_date) == 0  and len(amount_spent) == 0:
        return HttpResponse( "Error,  <b>Expense Date</b>  and <b> Amount Spent</b> are required fields:"  )
    if len(expense_date) == 0:
        return HttpResponse( "Error, <b>Expense Date</b> is a required field:") 
    if len(amount_spent) == 0:  
        return HttpResponse( "Error, <b>Amount Spent</b> is a required field:" )
    if float(amount_spent) <=  0:
        return HttpResponse( "Error, <b>Amount spent</b> must be greater than zero:") 
    exp.expenseCategory = ExpenseCategory(expenseCategory)
    exp.expenseType = ExpenseType(expenseType)
    exp.vendorType = VendorType(vendorType)
    exp.expense_date = datetime.datetime.strptime(expense_date,'%b %d, %Y')  
    exp.amount_spent = amount_spent
    exp.created_by = request.user
    #exp.comments =  "TEST" 

    exp.save()
    return HttpResponse("Success, Expense Record has been updated successfully.")

@login_required(login_url='/login')
@csrf_exempt
def delete_expense(request):
    print "Into delete_expense"
    logger.info("Into delete_expense() :" ) 
    id = request.POST["id"]
    print "Deleted Record is :" 
    print id
    try:
        exp = Expense.objects.get(pk=id)
    except ObjectDoesNotExist:
        return HttpResponse("Error, Could not find record for id : " + id   ) 
    exp.delete()      
    return HttpResponse("Success, Expense Record has been deleted successfully.")

@login_required(login_url='/login')
def upload_target(request):
    logger.info("Into upload_target() :" ) 
    print "Into upload target"
    userName = None
    logger.info ("Into upload_target:" ) 
    if request.user.is_authenticated():
        userName = request.user.username
    print userName
    logger.info(userName)
    u = User.objects.get(username=userName) 
    if u == None:
        logger.info("User is not authenticated:" ) 
        messages.error(request, "User is not authenticated. Please login." )
    if request.method == "GET":
        print "Method is Get, Return back."
        logger.info("Into Method Get, Return back." )
        return render (request, 'admintool/upload_target.html')
    if request.method == "POST":
        print "Method is POST, process csv file:" 
        logger.info("Into method Post, process csv File:" ) 
        # if the file is not uploaded
        if not request.FILES:
            messages.error(request, "Please choose a file to upload:")
            return render( request, 'admintool/upload_target.html',)
        rowList= []
        errorList=[]
        file=request.FILES['targetfile']
        dataReader=csv.reader(file.read().splitlines())
        for row in dataReader:
            print "Into for loop :" 
            # Empty or incomplete file
            if len(row[0])==0 or len(row[1])==0 or len(row[2])==0 or len(row[3])==0:
               errorList.append(row)
            # Get expenseCategory_id from the ExpenseCategory value.
            else:
                try: 
                    ec = ExpenseCategory.objects.get(category_name  = row[1].strip() )
                except ObjectDoesNotExist:
                    # Add to  errorList
                    errorList.append(row) 
                    break  # Get out of the else block.
                print "ec.id is :" + str(ec.id  ) 
                try:
                    # Check whether the record has already been uploaded.
                    et=ExpenseTarget.objects.get(plan_type=row[0].strip(), expenseCategory_id=ec.id, yr_m=row[2].strip())
                    if et:
                        #Record already  exists
                        print "Expense Target object already  exists" 
                        errorList.append(row) 
                except ObjectDoesNotExist:    
                    #record needs to be inserted into ExpenseTarget
                    # Insert into pristineList
                    print "Adding to  rowlist :" 
                    rowList.append(row)  
                except MultipleObjectsReturned:
                    #if dupes exist
                    print "Adding to errorList"
                    errorList.append(row)
        #Iterate rowList and insert into DB
    for validRow in rowList:    
        print "Saving records to DB: " 
        target=ExpenseTarget( plan_type = validRow[0].strip(),  expenseCategory=ExpenseCategory(ec.id ), yr_m = validRow[2].strip(), amount=validRow[3], user=User(u.id) ) 
        target.save()  
    if len(rowList)> 0:
        print "Printing RowList:" 
        messages.success( request, "File uploaded successfully. Number of records uploaded:  " + str( len(rowList))  ) 
    if len(errorList) > 0:
        print "Printing ErrorList" 

templates/admintool/add_expense.html
{% extends 'base.html' %}
   {% block customjsfunctions %}
    $(function() {
       $( "#id_expense_date" ).datepicker({dateFormat:'M dd, yy'});
  });
  {% endblock %}
 {% block content %}

    {% if messages %} 
      {% for message in messages %}
      
      <p>   {{ message }} </p>
      {% endfor  %}
    {% endif %}
    
    {% block title %} Add Expenses {% endblock %}
 
      <div>
        <form id="add_expense_form" method="post" action={%url 'save_expense' %} >
        {% csrf_token  %}
        <table>
           <tr><td class="center" colspan="2"><b>Add new Expense:</b></td> </tr>
            {% for field in form %}
                <tr>
                    <td> {{ field.label_tag }}</td><td> {{ field }}</td>  
            {% endfor %}
                </tr>
        </table>
            <input type ="submit" id="add_button_id"  name="Add Expense"  value="Submit"  />
       
        </form>
      </div>
<br>
    

{% endblock %}

templates/admintool/index.html
{% extends 'base.html' %}



   {% block customjsfunctions %}
    $(function() {
       $( "#id_expense_date" ).datepicker({dateFormat:'M dd, yy'});
  });

  $(document).ready(function(){
   //alert('Into  document.ready')
     $("#errorDiv").dialog({autoOpen:false,bgiframe:true,
                            closeOnEscape:true, title:'Application Error',
                            buttons:{"Ok": function() { $(this).dialog("close");}}});
     $("#messageDiv").dialog({autoOpen:false,bgiframe:true,
                            closeOnEscape:true, title:'Application Message',
                            buttons:{"Ok": function() { $(this).dialog("close");}}});

//     var form  = $('#add_expense_form');
//     var submit = $('#submit');
//     form.on('submit', function(e) {
//        e.preventDefault(); 

   // $(":button").click(function(){
      $(".graybtn").click(function(){
//       alert($(this).attr('id'));
       var id  =  $(this).attr('id');
       var res = id.split("_")
       var oper = res[0];
       var key = res[1];

       if ( oper == "up") { // Update Record 
            
            var newDateSpent = $("#id_expense_date_"+key).val()
            var newCategory = $("#id_expenseCategory_"+key).val()
            var newAmount = $("#id_amount_"+key).val()
            var newPaymentType = $("#id_expense_type_"+key).val()
            var newVendor = $("#id_vendor_type_"+key).val()
            
            jQuery.post( "{%url 'update_expense' %}", 
                     {"id":key, 
                      "expense_date":newDateSpent,
                      "expenseCategory":newCategory,
                      "amount_spent":newAmount,
                      "expenseType":newPaymentType,
                      "vendorType":newVendor},
                      function(response){
                        if(response.substring(0,5) == "Error"){
                            $("#errorBody").html(response);
                            $("#errorDiv").dialog("open");
                        }
                        else{
                            $("#tr_"+key).effect("highlight",{color:"green"}, 6000);
                           $("#messageBody").html(response);
                            $("#messageDiv").dialog("open");
                        }//else close
                      }//function response
                      ) //post update
                      
} else if (oper == "dl"  )  { // Delete Record
         $("#tr_"+key).effect("highlight",{color:"orange"},6000);
         var delPrompt = confirm("Are you sure you  want to  delete this Expense record?");
         if(delPrompt){
         jQuery.post("{% url 'delete_expense' %}", 
                      {"id":key },
                      function(response){
                       if(response.substring(0,5) == "Error" ){  
                         $("#errorBody").html(response);
                         $("#errorDiv").dialog("open");
                      }else{
                         $("#tr_"+key).remove();
                         $("#messageBody").html(response);
                         $("#messageDiv").dialog("open");
                      }// end of else   

            } // end of function(response)
         );// matching with parenthesis before delete_expense
       } // if(delPrompt) 
    } // if( oper =="dl") 
   });

 //  $(":text").click(function(){
   $(".datepick").click(function(){
//       alert($(this).attr('id'));
       var id = $(this).attr('id');
  //     var idx = "'"+"#"+id+"'"
      $('#'+id).datepicker({dateFormat:'M dd, yy'});
  });
// }); // form.on
}); //End of document.ready(function)

{% endblock %}



{% block content %}




{% block title %}<h1> Expenses List </h1>{% endblock %}

    {% if messages %} 
      {% for message in messages %}
      <p>   {{ message }} </p>
      {% endfor  %}
    {% endif %}


{{request.session.is_expense_added}}
 {% ifequal request.session.is_expense_added True %}
        <p> Expense added successfully </p>
    {% endifequal %}
 
{% if all_expenses %}

<div >
<table border="1" cellspacing="0" cellpadding="3px"   >
   <tr><td class="center" colspan="8"  ><b>Your Expenses</b></td> <tr>
    <tr>
        <td align="center"><strong>Select All</strong></td>
        <td align="left"><strong>Date Spent</strong></td>
        <td align="left"><strong>Category</strong></td>
        <td align="left"><strong>Amount</strong></td>
        <td align="left"><strong>Payment Type</strong></td>
        <td align="left"><strong>Vendor</strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>

    </tr>
{% for expense in all_expenses %}
    <tr id ="tr_{{expense.id}}" value="{{expense.id}}">

    <td id = "{{expense.id}}" >
    <input type ="checkbox" id="id_checkbox_{{expense.id}}"/></td>
    <td><input type="text" class="datepick" id="id_expense_date_{{expense.id}}" value="{{expense.expense_date|date:"M d, Y"}}"/></td>

{% if expenseCategory %}
<td><select id="id_expenseCategory_{{expense.id}}" name="expenseCategory">
   {% for cat in expenseCategory %}
       <option value="{{cat.id }}"   {% if cat.id ==  expense.expenseCategory_id %} selected="selected" {% endif %} >  {{cat.category_name }}  </option>
    {% endfor %} 
 </select>
</td>
{% endif %} 
    <td><input type="text"  id="id_amount_{{expense.id}}" value="{{expense.amount_spent}}"/></td>

{% if expenseType %}
    <td><select id="id_expense_type_{{expense.id}}" name="expenseType" >
     {% for typ in expenseType %}
        <option value="{{typ.id}}" {% if typ.id == expense.expenseType_id %} selected="selected" {% endif %}> {{typ.type_name }} </option>
    {% endfor %}
  </select>
 </td>
{% endif %} 


{% if vendorType %}
    <td><select id="id_vendor_type_{{expense.id}}" name="vendorType" >
    {% for vtyp in vendorType %} 
       <option value="{{vtyp.id }}" {% if vtyp.id == expense.vendorType_id %} selected="selected" {% endif %}> {{vtyp.vendor_name}} </option>
    {% endfor %}
   </select>
   </td>
 {% endif %}

  <td><input name="Button" class="graybtn"  id="up_{{expense.id}}" type="button"  value="Update"/></td>
  <td><input name="Button" class="graybtn"  id="dl_{{expense.id}}" type="button"  value="Delete"/></td>

 
 </tr>
{% endfor %}
</table>

<table>
 <tr>
    <td><input name="Button" class="graybtn" id="upall_checked" type="button" value="Update All"/></td>
    <td><input name="Button" class="graybtn" id="delall_checked" type="button" value="Delete All"/></td>
 </tr>
</table>

</div>
 <div id="errorDiv">
    <span id="errorBody"></span>
 </div>

 <div id="messageDiv">
   <span id="messageBody"</span> 
 </div>

<br />


{% endif %}

   <div class="left">
  <table>
   <tr>
    <td >
     <ul>
        <li><a href="{% url 'add_expense' %}" id="add_expense_link_id"> Add Expense</a></li>
        <li><a href="{% url 'upload_expense_csv' %}"> Upload Targets</a></li>
     </ul>
     </td>
    </tr>
   </table>
   </div>


{% endblock %}

templates/admintool/upload_target.html
{%extends "base.html" %}




{% block content  %}

    {% if messages %} 
      {% for message in messages %}
          <p>   {{ message }} </p>
      {% endfor  %}
    {% endif %}
    
    <table border="1" cellspacing="0" cellpadding="3px">
       <tr><td align="center"<strong><b>Upload Targets</b></strong></td></tr>
       <tr><td>
          <p style="width:500px">Upload Target/Forecast csv file here. The data 
        must be in the following format:<br> <b>Plan Type</b>,<b>Expense Category</b>,<b>Year Month</b>, <b>Amount</b>  </p> 

    <form id="upload_form" method="post" action="{% url 'upload_expense_csv' %}" enctype="multipart/form-data">
     {% csrf_token  %}
         <table>
          <tr><td> <input type="file" name="targetfile"  size="110" /></td></tr>         </table> 
         <input type="submit" name="submit"  value="Upload" />
     </form>

   <font color="green">
    <strong>Please be patient. This process may  take a few seconds depending on the number of records.</strong><br/>
   </font> 
{% endblock %}